# OpenAI Codex CLI Configuration for CloudBase AI ToolKit
# This configuration enables CloudBase MCP tools in OpenAI Codex CLI

[mcp_servers.cloudbase]
command = "npx"
args = ["-y", "@cloudbase/cloudbase-mcp@latest"]