/**
 * 自动生成的 TCB 对外 API Action 列表
 * 从 references/ 目录下的文档中提取
 *
 * ⚠️ 请勿手动编辑此文件，由 scripts/generate-actionlist.ts 自动生成
 *
 * Action 数量: 70
 */

const TCB_ALLOWED_ACTIONS: string[] = [
  'AddProvider',
  'BindCloudBaseAccessDomain',
  'BindCloudBaseGWDomain',
  'CheckTcbService',
  'CreateAuthDomain',
  'CreateBillDeal',
  'CreateCloudBaseGWAPI',
  'CreateEnv',
  'CreateEnvResource',
  'CreateHostingDomain',
  'CreateMySQL',
  'CreateStaticStore',
  'CreateTable',
  'CreateUser',
  'DeleteAuthDomain',
  'DeleteCloudBaseGWAPI',
  'DeleteCloudBaseGWDomain',
  'DeleteProvider',
  'DeleteTable',
  'DeleteUsers',
  'DeleteVmInstance',
  'DescribeAuthDomains',
  'DescribeBaasPackageList',
  'DescribeBillingInfo',
  'DescribeClient',
  'DescribeCloudBaseBuildService',
  'DescribeCloudBaseGWAPI',
  'DescribeCloudBaseGWService',
  'DescribeCloudBaseRunServerVersion',
  'DescribeCreateMySQLResult',
  'DescribeCurveData',
  'DescribeDatabaseACL',
  'DescribeEnvAccountCircle',
  'DescribeEnvLimit',
  'DescribeEnvs',
  'DescribeHostingDomainTask',
  'DescribeLoginConfig',
  'DescribeMySQLClusterDetail',
  'DescribeMySQLTaskStatus',
  'DescribeQuotaData',
  'DescribeSafeRule',
  'DescribeStaticStore',
  'DescribeTable',
  'DescribeTables',
  'DescribeUserList',
  'DescribeVmInstances',
  'DescribeVmSpec',
  'DestroyEnv',
  'DestroyMySQL',
  'DestroyStaticStore',
  'EditAuthConfig',
  'GetProviders',
  'InquireVmPrice',
  'ListTables',
  'ModifyClient',
  'ModifyCloudBaseGWAPI',
  'ModifyClsTopic',
  'ModifyDatabaseACL',
  'ModifyEnv',
  'ModifyEnvPlan',
  'ModifyLoginConfig',
  'ModifyProvider',
  'ModifySafeRule',
  'ModifyUser',
  'ReinstateEnv',
  'RenewEnv',
  'RunCommands',
  'RunSql',
  'SearchClsLog',
  'UpdateTable',
];

export default TCB_ALLOWED_ACTIONS;
